In [2]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
matrix = np.random.randint(1, 11, (5, 5))
print(matrix)

[[10  9  2  5  1]
 [ 3  7  9 10  5]
 [ 2  1  9 10  6]
 [ 3  1 10  3  8]
 [ 1  6  5 10  2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [8]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.19373054 0.32221439 0.68963294 0.05534331]
 [0.48682419 0.35362085 0.94269694 0.9417958 ]
 [0.06645071 0.35635848 0.26204433 0.99780623]
 [0.39125028 0.76844593 0.9330771  0.88093548]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [11]:
vector1 = np.random.randint(1, 11, 5)
vector2 = np.random.randint(1, 11, 5)
add = vector1 + vector2
sub = vector1 - vector2
mul = vector1 * vector2

print(vector1)
print(vector2)
print(add)
print(sub)
print(mul)

[6 3 8 3 4]
[ 6  3  6  2 10]
[12  6 14  5 14]
[ 0  0  2  1 -6]
[36  9 48  6 40]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [13]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([8, 9, 10, 11, 12, 13, 14])
scalar = np.dot(vector1, vector2)
print(scalar)

336


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [18]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
mul = np.dot(matrix1, matrix2)

print(matrix1)
print("")
print(matrix2)
print("")
print(mul)

[[ 2  5]
 [10  5]]

[[ 8  5 10]
 [ 7  2  7]]

[[ 51  20  55]
 [115  60 135]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.



In [23]:
matrix = np.random.randint(1, 11, (3, 3))
matrix_inv = np.linalg.inv(matrix)


print(matrix)
print("")
print(matrix_inv)

[[2 2 2]
 [4 9 7]
 [4 4 8]]

[[ 1.1  -0.2  -0.1 ]
 [-0.1   0.2  -0.15]
 [-0.5  -0.    0.25]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [28]:
matrix = np.random.rand(4, 4)
t_matrix = matrix.T

print(matrix)
print("")
print(t_matrix)

[[0.03629763 0.71440918 0.21960804 0.99419647]
 [0.02294794 0.55441998 0.36247756 0.25110091]
 [0.32319644 0.10967142 0.17707227 0.50287256]
 [0.17194186 0.25743229 0.20867613 0.08020121]]

[[0.03629763 0.02294794 0.32319644 0.17194186]
 [0.71440918 0.55441998 0.10967142 0.25743229]
 [0.21960804 0.36247756 0.17707227 0.20867613]
 [0.99419647 0.25110091 0.50287256 0.08020121]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [31]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1, 11, 4)
mul = np.dot(matrix, vector)

print(matrix)
print("")
print(vector)
print("")
print(mul)

[[10  7  7  9]
 [ 3  9  7  2]
 [ 6  9 10  8]]

[3 7 5 3]

[141 113 155]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [32]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
mul = np.dot(matrix, vector)

print(matrix)
print("")
print(vector)
print("")
print(mul)

[[0.44403528 0.49059361 0.55895682]
 [0.44159626 0.45653686 0.60550327]]

[0.40574585 0.74735965 0.1065086 ]

[0.60634906 0.58486439]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [34]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
mul = matrix1 * matrix2

print(matrix1)
print("")
print(matrix2)
print("")
print(mul)

[[2 5]
 [7 4]]

[[8 3]
 [2 7]]

[[16 15]
 [14 28]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [36]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 2))
mul = np.dot(matrix1, matrix2)


print(matrix1)
print("")
print(matrix2)
print("")
print(mul)

[[3 5]
 [5 7]]

[[8 7]
 [3 1]]

[[39 26]
 [61 42]]

[[24 35]
 [15  7]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [38]:
matrix = np.random.randint(1, 101, (5, 5))
sum = matrix.sum()

print(matrix)
print("")
print(sum)

[[81 92 67 35 33]
 [38 17 74 84 31]
 [ 2 93 69 64  9]
 [63 48 79  6 64]
 [ 2 96 40 62 70]]

1319


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [39]:
matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))
sub = matrix1 - matrix2

print(matrix1)
print("")
print(matrix2)
print("")
print(sub)

[[10  6  2  1]
 [ 5  4  6  1]
 [ 7  4  8  7]
 [ 9  3 10  9]]

[[ 7  9  3  4]
 [ 5  7  7  4]
 [ 3  7  2  2]
 [ 2  8 10  1]]

[[ 3 -3 -1 -3]
 [ 0 -3 -1 -3]
 [ 4 -3  6  5]
 [ 7 -5  0  8]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [46]:
matrix = np.random.rand(3, 3)
row_sums = np.sum(matrix, axis=1)
c_vector = row_sums.reshape(-1, 1)

print(matrix)
print(row_sums)
print(c_vector)


[[0.27637935 0.74314084 0.79376262]
 [0.05553152 0.80847087 0.61942674]
 [0.58917182 0.2129698  0.38892748]]
[1.81328281 1.48342914 1.1910691 ]
[[1.81328281]
 [1.48342914]
 [1.1910691 ]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [48]:
matrix = np.random.randint(-10, 11, (3, 4))
sq = np.square(matrix)

print(matrix)
print("")
print(sq)

[[ 5 -3  8  1]
 [ 6 -4  9 -5]
 [-5 -2 10 -4]]

[[ 25   9  64   1]
 [ 36  16  81  25]
 [ 25   4 100  16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [51]:
vector = np.random.randint(1, 51, 4)
sq = np.sqrt(vector)


print(vector)
print("")
print(sq)


[32 41 37 39]

[1024 1681 1369 1521]

[5.65685425 6.40312424 6.08276253 6.244998  ]
